// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Aya.CompiledModels
{
    public partial class AyaDbContextModel
    {
        private AyaDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("3bb43489-4bad-4a23-9874-f4ad595f6ac9"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var fileEntity = FileEntityEntityType.Create(this);
            var eventEntity = EventEntityEntityType.Create(this);
            var migrationEntity = MigrationEntityEntityType.Create(this);

            FileEntityEntityType.CreateAnnotations(fileEntity);
            EventEntityEntityType.CreateAnnotations(eventEntity);
            MigrationEntityEntityType.CreateAnnotations(migrationEntity);

            AddAnnotation("ProductVersion", "10.0.1");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var fileEntity = FindEntityType("Aya.Contract.Models.FileEntity")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            fileEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var ayaContractModelsFileEntityTableBase = new TableBase("Aya.Contract.Models.FileEntity", null, relationalModel);
            var hostColumnBase = new ColumnBase<ColumnMappingBase>("Host", "TEXT", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Host", hostColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "TEXT", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Id", idColumnBase);
            var loginColumnBase = new ColumnBase<ColumnMappingBase>("Login", "TEXT", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Login", loginColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Name", nameColumnBase);
            var passwordColumnBase = new ColumnBase<ColumnMappingBase>("Password", "TEXT", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Password", passwordColumnBase);
            var pathColumnBase = new ColumnBase<ColumnMappingBase>("Path", "TEXT", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Path", pathColumnBase);
            var typeColumnBase = new ColumnBase<ColumnMappingBase>("Type", "INTEGER", ayaContractModelsFileEntityTableBase);
            ayaContractModelsFileEntityTableBase.Columns.Add("Type", typeColumnBase);
            relationalModel.DefaultTables.Add("Aya.Contract.Models.FileEntity", ayaContractModelsFileEntityTableBase);
            var ayaContractModelsFileEntityMappingBase = new TableMappingBase<ColumnMappingBase>(fileEntity, ayaContractModelsFileEntityTableBase, null);
            ayaContractModelsFileEntityTableBase.AddTypeMapping(ayaContractModelsFileEntityMappingBase, false);
            defaultTableMappings.Add(ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, fileEntity.FindProperty("Id")!, ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)hostColumnBase, fileEntity.FindProperty("Host")!, ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)loginColumnBase, fileEntity.FindProperty("Login")!, ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, fileEntity.FindProperty("Name")!, ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)passwordColumnBase, fileEntity.FindProperty("Password")!, ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)pathColumnBase, fileEntity.FindProperty("Path")!, ayaContractModelsFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)typeColumnBase, fileEntity.FindProperty("Type")!, ayaContractModelsFileEntityMappingBase);

            var tableMappings = new List<TableMapping>();
            fileEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var filesTable = new Table("Files", null, relationalModel);
            var idColumn = new Column("Id", "TEXT", filesTable);
            filesTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn);
            var hostColumn = new Column("Host", "TEXT", filesTable);
            filesTable.Columns.Add("Host", hostColumn);
            hostColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(hostColumn);
            var loginColumn = new Column("Login", "TEXT", filesTable);
            filesTable.Columns.Add("Login", loginColumn);
            loginColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(loginColumn);
            var nameColumn = new Column("Name", "TEXT", filesTable);
            filesTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            var passwordColumn = new Column("Password", "TEXT", filesTable);
            filesTable.Columns.Add("Password", passwordColumn);
            passwordColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(passwordColumn);
            var pathColumn = new Column("Path", "TEXT", filesTable);
            filesTable.Columns.Add("Path", pathColumn);
            pathColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(pathColumn);
            var typeColumn = new Column("Type", "INTEGER", filesTable);
            filesTable.Columns.Add("Type", typeColumn);
            typeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(typeColumn);
            relationalModel.Tables.Add(("Files", null), filesTable);
            var filesTableMapping = new TableMapping(fileEntity, filesTable, null);
            filesTable.AddTypeMapping(filesTableMapping, false);
            tableMappings.Add(filesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, fileEntity.FindProperty("Id")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(hostColumn, fileEntity.FindProperty("Host")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(loginColumn, fileEntity.FindProperty("Login")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, fileEntity.FindProperty("Name")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(passwordColumn, fileEntity.FindProperty("Password")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(pathColumn, fileEntity.FindProperty("Path")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(typeColumn, fileEntity.FindProperty("Type")!, filesTableMapping);
            var pK_Files = new UniqueConstraint("PK_Files", filesTable, new[] { idColumn });
            filesTable.PrimaryKey = pK_Files;
            pK_Files.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Files));
            var pK_FilesKey = RelationalModel.GetKey(this,
                "Aya.Contract.Models.FileEntity",
                new[] { "Id" });
            pK_Files.MappedKeys.Add(pK_FilesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_FilesKey).Add(pK_Files);
            filesTable.UniqueConstraints.Add("PK_Files", pK_Files);

            var eventEntity = FindEntityType("Nestor.Db.Models.EventEntity")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            eventEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var nestorDbModelsEventEntityTableBase = new TableBase("Nestor.Db.Models.EventEntity", null, relationalModel);
            var createdAtColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAt", "TEXT", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase);
            var entityBooleanValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityBooleanValue", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityBooleanValue", entityBooleanValueColumnBase);
            var entityByteArrayValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityByteArrayValue", "BLOB", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityByteArrayValue", entityByteArrayValueColumnBase);
            var entityByteValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityByteValue", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityByteValue", entityByteValueColumnBase);
            var entityCharValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityCharValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityCharValue", entityCharValueColumnBase);
            var entityDateOnlyValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityDateOnlyValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityDateOnlyValue", entityDateOnlyValueColumnBase);
            var entityDateTimeOffsetValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityDateTimeOffsetValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityDateTimeOffsetValue", entityDateTimeOffsetValueColumnBase);
            var entityDateTimeValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityDateTimeValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityDateTimeValue", entityDateTimeValueColumnBase);
            var entityDecimalValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityDecimalValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityDecimalValue", entityDecimalValueColumnBase);
            var entityDoubleValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityDoubleValue", "REAL", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityDoubleValue", entityDoubleValueColumnBase);
            var entityGuidValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityGuidValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityGuidValue", entityGuidValueColumnBase);
            var entityIdColumnBase = new ColumnBase<ColumnMappingBase>("EntityId", "TEXT", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityId", entityIdColumnBase);
            var entityInt16ValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityInt16Value", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityInt16Value", entityInt16ValueColumnBase);
            var entityInt32ValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityInt32Value", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityInt32Value", entityInt32ValueColumnBase);
            var entityInt64ValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityInt64Value", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityInt64Value", entityInt64ValueColumnBase);
            var entityPropertyColumnBase = new ColumnBase<ColumnMappingBase>("EntityProperty", "TEXT", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityProperty", entityPropertyColumnBase);
            var entitySByteValueColumnBase = new ColumnBase<ColumnMappingBase>("EntitySByteValue", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntitySByteValue", entitySByteValueColumnBase);
            var entitySingleValueColumnBase = new ColumnBase<ColumnMappingBase>("EntitySingleValue", "REAL", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntitySingleValue", entitySingleValueColumnBase);
            var entityStringValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityStringValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityStringValue", entityStringValueColumnBase);
            var entityTimeOnlyValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityTimeOnlyValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityTimeOnlyValue", entityTimeOnlyValueColumnBase);
            var entityTimeSpanValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityTimeSpanValue", "TEXT", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityTimeSpanValue", entityTimeSpanValueColumnBase);
            var entityTypeColumnBase = new ColumnBase<ColumnMappingBase>("EntityType", "TEXT", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityType", entityTypeColumnBase);
            var entityUInt16ValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityUInt16Value", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityUInt16Value", entityUInt16ValueColumnBase);
            var entityUInt32ValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityUInt32Value", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityUInt32Value", entityUInt32ValueColumnBase);
            var entityUInt64ValueColumnBase = new ColumnBase<ColumnMappingBase>("EntityUInt64Value", "INTEGER", nestorDbModelsEventEntityTableBase)
            {
                IsNullable = true
            };
            nestorDbModelsEventEntityTableBase.Columns.Add("EntityUInt64Value", entityUInt64ValueColumnBase);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("Id", idColumnBase0);
            var transactionIdColumnBase = new ColumnBase<ColumnMappingBase>("TransactionId", "TEXT", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("TransactionId", transactionIdColumnBase);
            var userIdColumnBase = new ColumnBase<ColumnMappingBase>("UserId", "TEXT", nestorDbModelsEventEntityTableBase);
            nestorDbModelsEventEntityTableBase.Columns.Add("UserId", userIdColumnBase);
            relationalModel.DefaultTables.Add("Nestor.Db.Models.EventEntity", nestorDbModelsEventEntityTableBase);
            var nestorDbModelsEventEntityMappingBase = new TableMappingBase<ColumnMappingBase>(eventEntity, nestorDbModelsEventEntityTableBase, null);
            nestorDbModelsEventEntityTableBase.AddTypeMapping(nestorDbModelsEventEntityMappingBase, false);
            defaultTableMappings0.Add(nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, eventEntity.FindProperty("Id")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase, eventEntity.FindProperty("CreatedAt")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityBooleanValueColumnBase, eventEntity.FindProperty("EntityBooleanValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityByteArrayValueColumnBase, eventEntity.FindProperty("EntityByteArrayValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityByteValueColumnBase, eventEntity.FindProperty("EntityByteValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityCharValueColumnBase, eventEntity.FindProperty("EntityCharValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityDateOnlyValueColumnBase, eventEntity.FindProperty("EntityDateOnlyValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityDateTimeOffsetValueColumnBase, eventEntity.FindProperty("EntityDateTimeOffsetValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityDateTimeValueColumnBase, eventEntity.FindProperty("EntityDateTimeValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityDecimalValueColumnBase, eventEntity.FindProperty("EntityDecimalValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityDoubleValueColumnBase, eventEntity.FindProperty("EntityDoubleValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityGuidValueColumnBase, eventEntity.FindProperty("EntityGuidValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityIdColumnBase, eventEntity.FindProperty("EntityId")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityInt16ValueColumnBase, eventEntity.FindProperty("EntityInt16Value")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityInt32ValueColumnBase, eventEntity.FindProperty("EntityInt32Value")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityInt64ValueColumnBase, eventEntity.FindProperty("EntityInt64Value")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityPropertyColumnBase, eventEntity.FindProperty("EntityProperty")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entitySByteValueColumnBase, eventEntity.FindProperty("EntitySByteValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entitySingleValueColumnBase, eventEntity.FindProperty("EntitySingleValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityStringValueColumnBase, eventEntity.FindProperty("EntityStringValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityTimeOnlyValueColumnBase, eventEntity.FindProperty("EntityTimeOnlyValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityTimeSpanValueColumnBase, eventEntity.FindProperty("EntityTimeSpanValue")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityTypeColumnBase, eventEntity.FindProperty("EntityType")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityUInt16ValueColumnBase, eventEntity.FindProperty("EntityUInt16Value")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityUInt32ValueColumnBase, eventEntity.FindProperty("EntityUInt32Value")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityUInt64ValueColumnBase, eventEntity.FindProperty("EntityUInt64Value")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)transactionIdColumnBase, eventEntity.FindProperty("TransactionId")!, nestorDbModelsEventEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase, eventEntity.FindProperty("UserId")!, nestorDbModelsEventEntityMappingBase);

            var tableMappings0 = new List<TableMapping>();
            eventEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var eventsTable = new Table("Events", null, relationalModel);
            var idColumn0 = new Column("Id", "INTEGER", eventsTable);
            eventsTable.Columns.Add("Id", idColumn0);
            idColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(idColumn0);
            var createdAtColumn = new Column("CreatedAt", "TEXT", eventsTable);
            eventsTable.Columns.Add("CreatedAt", createdAtColumn);
            createdAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(createdAtColumn);
            var entityBooleanValueColumn = new Column("EntityBooleanValue", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityBooleanValue", entityBooleanValueColumn);
            entityBooleanValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(entityBooleanValueColumn);
            var entityByteArrayValueColumn = new Column("EntityByteArrayValue", "BLOB", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityByteArrayValue", entityByteArrayValueColumn);
            entityByteArrayValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<byte[]>(entityByteArrayValueColumn);
            var entityByteValueColumn = new Column("EntityByteValue", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityByteValue", entityByteValueColumn);
            entityByteValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<byte>(entityByteValueColumn);
            var entityCharValueColumn = new Column("EntityCharValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityCharValue", entityCharValueColumn);
            entityCharValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<char>(entityCharValueColumn);
            var entityDateOnlyValueColumn = new Column("EntityDateOnlyValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityDateOnlyValue", entityDateOnlyValueColumn);
            entityDateOnlyValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateOnly>(entityDateOnlyValueColumn);
            var entityDateTimeOffsetValueColumn = new Column("EntityDateTimeOffsetValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityDateTimeOffsetValue", entityDateTimeOffsetValueColumn);
            entityDateTimeOffsetValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(entityDateTimeOffsetValueColumn);
            var entityDateTimeValueColumn = new Column("EntityDateTimeValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityDateTimeValue", entityDateTimeValueColumn);
            entityDateTimeValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(entityDateTimeValueColumn);
            var entityDecimalValueColumn = new Column("EntityDecimalValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityDecimalValue", entityDecimalValueColumn);
            entityDecimalValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<decimal>(entityDecimalValueColumn);
            var entityDoubleValueColumn = new Column("EntityDoubleValue", "REAL", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityDoubleValue", entityDoubleValueColumn);
            entityDoubleValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<double>(entityDoubleValueColumn);
            var entityGuidValueColumn = new Column("EntityGuidValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityGuidValue", entityGuidValueColumn);
            entityGuidValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(entityGuidValueColumn);
            var entityIdColumn = new Column("EntityId", "TEXT", eventsTable);
            eventsTable.Columns.Add("EntityId", entityIdColumn);
            entityIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(entityIdColumn);
            var entityInt16ValueColumn = new Column("EntityInt16Value", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityInt16Value", entityInt16ValueColumn);
            entityInt16ValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<short>(entityInt16ValueColumn);
            var entityInt32ValueColumn = new Column("EntityInt32Value", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityInt32Value", entityInt32ValueColumn);
            entityInt32ValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(entityInt32ValueColumn);
            var entityInt64ValueColumn = new Column("EntityInt64Value", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityInt64Value", entityInt64ValueColumn);
            entityInt64ValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(entityInt64ValueColumn);
            var entityPropertyColumn = new Column("EntityProperty", "TEXT", eventsTable);
            eventsTable.Columns.Add("EntityProperty", entityPropertyColumn);
            entityPropertyColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(entityPropertyColumn);
            var entitySByteValueColumn = new Column("EntitySByteValue", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntitySByteValue", entitySByteValueColumn);
            entitySByteValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<sbyte>(entitySByteValueColumn);
            var entitySingleValueColumn = new Column("EntitySingleValue", "REAL", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntitySingleValue", entitySingleValueColumn);
            entitySingleValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<float>(entitySingleValueColumn);
            var entityStringValueColumn = new Column("EntityStringValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityStringValue", entityStringValueColumn);
            entityStringValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(entityStringValueColumn);
            var entityTimeOnlyValueColumn = new Column("EntityTimeOnlyValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityTimeOnlyValue", entityTimeOnlyValueColumn);
            entityTimeOnlyValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<TimeOnly>(entityTimeOnlyValueColumn);
            var entityTimeSpanValueColumn = new Column("EntityTimeSpanValue", "TEXT", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityTimeSpanValue", entityTimeSpanValueColumn);
            entityTimeSpanValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<TimeSpan>(entityTimeSpanValueColumn);
            var entityTypeColumn = new Column("EntityType", "TEXT", eventsTable);
            eventsTable.Columns.Add("EntityType", entityTypeColumn);
            entityTypeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(entityTypeColumn);
            var entityUInt16ValueColumn = new Column("EntityUInt16Value", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityUInt16Value", entityUInt16ValueColumn);
            entityUInt16ValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<ushort>(entityUInt16ValueColumn);
            var entityUInt32ValueColumn = new Column("EntityUInt32Value", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityUInt32Value", entityUInt32ValueColumn);
            entityUInt32ValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<uint>(entityUInt32ValueColumn);
            var entityUInt64ValueColumn = new Column("EntityUInt64Value", "INTEGER", eventsTable)
            {
                IsNullable = true
            };
            eventsTable.Columns.Add("EntityUInt64Value", entityUInt64ValueColumn);
            entityUInt64ValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<ulong>(entityUInt64ValueColumn);
            var transactionIdColumn = new Column("TransactionId", "TEXT", eventsTable);
            eventsTable.Columns.Add("TransactionId", transactionIdColumn);
            transactionIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(transactionIdColumn);
            var userIdColumn = new Column("UserId", "TEXT", eventsTable);
            eventsTable.Columns.Add("UserId", userIdColumn);
            userIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(userIdColumn);
            relationalModel.Tables.Add(("Events", null), eventsTable);
            var eventsTableMapping = new TableMapping(eventEntity, eventsTable, null);
            eventsTable.AddTypeMapping(eventsTableMapping, false);
            tableMappings0.Add(eventsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, eventEntity.FindProperty("Id")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn, eventEntity.FindProperty("CreatedAt")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityBooleanValueColumn, eventEntity.FindProperty("EntityBooleanValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityByteArrayValueColumn, eventEntity.FindProperty("EntityByteArrayValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityByteValueColumn, eventEntity.FindProperty("EntityByteValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityCharValueColumn, eventEntity.FindProperty("EntityCharValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityDateOnlyValueColumn, eventEntity.FindProperty("EntityDateOnlyValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityDateTimeOffsetValueColumn, eventEntity.FindProperty("EntityDateTimeOffsetValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityDateTimeValueColumn, eventEntity.FindProperty("EntityDateTimeValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityDecimalValueColumn, eventEntity.FindProperty("EntityDecimalValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityDoubleValueColumn, eventEntity.FindProperty("EntityDoubleValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityGuidValueColumn, eventEntity.FindProperty("EntityGuidValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityIdColumn, eventEntity.FindProperty("EntityId")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityInt16ValueColumn, eventEntity.FindProperty("EntityInt16Value")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityInt32ValueColumn, eventEntity.FindProperty("EntityInt32Value")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityInt64ValueColumn, eventEntity.FindProperty("EntityInt64Value")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityPropertyColumn, eventEntity.FindProperty("EntityProperty")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entitySByteValueColumn, eventEntity.FindProperty("EntitySByteValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entitySingleValueColumn, eventEntity.FindProperty("EntitySingleValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityStringValueColumn, eventEntity.FindProperty("EntityStringValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityTimeOnlyValueColumn, eventEntity.FindProperty("EntityTimeOnlyValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityTimeSpanValueColumn, eventEntity.FindProperty("EntityTimeSpanValue")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityTypeColumn, eventEntity.FindProperty("EntityType")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityUInt16ValueColumn, eventEntity.FindProperty("EntityUInt16Value")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityUInt32ValueColumn, eventEntity.FindProperty("EntityUInt32Value")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(entityUInt64ValueColumn, eventEntity.FindProperty("EntityUInt64Value")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(transactionIdColumn, eventEntity.FindProperty("TransactionId")!, eventsTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn, eventEntity.FindProperty("UserId")!, eventsTableMapping);
            var pK_Events = new UniqueConstraint("PK_Events", eventsTable, new[] { idColumn0 });
            eventsTable.PrimaryKey = pK_Events;
            pK_Events.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<long>(pK_Events));
            var pK_EventsKey = RelationalModel.GetKey(this,
                "Nestor.Db.Models.EventEntity",
                new[] { "Id" });
            pK_Events.MappedKeys.Add(pK_EventsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_EventsKey).Add(pK_Events);
            eventsTable.UniqueConstraints.Add("PK_Events", pK_Events);

            var migrationEntity = FindEntityType("Nestor.Db.Models.MigrationEntity")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            migrationEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var nestorDbModelsMigrationEntityTableBase = new TableBase("Nestor.Db.Models.MigrationEntity", null, relationalModel);
            var idColumnBase1 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", nestorDbModelsMigrationEntityTableBase);
            nestorDbModelsMigrationEntityTableBase.Columns.Add("Id", idColumnBase1);
            var sqlColumnBase = new ColumnBase<ColumnMappingBase>("Sql", "TEXT", nestorDbModelsMigrationEntityTableBase);
            nestorDbModelsMigrationEntityTableBase.Columns.Add("Sql", sqlColumnBase);
            relationalModel.DefaultTables.Add("Nestor.Db.Models.MigrationEntity", nestorDbModelsMigrationEntityTableBase);
            var nestorDbModelsMigrationEntityMappingBase = new TableMappingBase<ColumnMappingBase>(migrationEntity, nestorDbModelsMigrationEntityTableBase, null);
            nestorDbModelsMigrationEntityTableBase.AddTypeMapping(nestorDbModelsMigrationEntityMappingBase, false);
            defaultTableMappings1.Add(nestorDbModelsMigrationEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase1, migrationEntity.FindProperty("Id")!, nestorDbModelsMigrationEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)sqlColumnBase, migrationEntity.FindProperty("Sql")!, nestorDbModelsMigrationEntityMappingBase);

            var tableMappings1 = new List<TableMapping>();
            migrationEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var migrationsTable = new Table("Migrations", null, relationalModel);
            var idColumn1 = new Column("Id", "INTEGER", migrationsTable);
            migrationsTable.Columns.Add("Id", idColumn1);
            idColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn1);
            var sqlColumn = new Column("Sql", "TEXT", migrationsTable);
            migrationsTable.Columns.Add("Sql", sqlColumn);
            sqlColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(sqlColumn);
            relationalModel.Tables.Add(("Migrations", null), migrationsTable);
            var migrationsTableMapping = new TableMapping(migrationEntity, migrationsTable, null);
            migrationsTable.AddTypeMapping(migrationsTableMapping, false);
            tableMappings1.Add(migrationsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn1, migrationEntity.FindProperty("Id")!, migrationsTableMapping);
            RelationalModel.CreateColumnMapping(sqlColumn, migrationEntity.FindProperty("Sql")!, migrationsTableMapping);
            var pK_Migrations = new UniqueConstraint("PK_Migrations", migrationsTable, new[] { idColumn1 });
            migrationsTable.PrimaryKey = pK_Migrations;
            pK_Migrations.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_Migrations));
            var pK_MigrationsKey = RelationalModel.GetKey(this,
                "Nestor.Db.Models.MigrationEntity",
                new[] { "Id" });
            pK_Migrations.MappedKeys.Add(pK_MigrationsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_MigrationsKey).Add(pK_Migrations);
            migrationsTable.UniqueConstraints.Add("PK_Migrations", pK_Migrations);
            return relationalModel.MakeReadOnly();
        }
    }
}
