// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Aya
{
    public partial class AyaDbContextModel
    {
        private AyaDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("64d1b245-d688-4d8c-b009-c6c08bd39a8f"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var fileEntity = FileEntityEntityType.Create(this);
            var eventEntity = EventEntityEntityType.Create(this);
            var migrationEntity = MigrationEntityEntityType.Create(this);

            FileEntityEntityType.CreateAnnotations(fileEntity);
            EventEntityEntityType.CreateAnnotations(eventEntity);
            MigrationEntityEntityType.CreateAnnotations(migrationEntity);

            AddAnnotation("ProductVersion", "10.0.1");
        }
    }
}
