// <auto-generated />
using Aya.CompiledModels;
using Aya.Services;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AyaDbContext), typeof(AyaDbContextModel))]
