// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Aya.CompiledModels
{
    public partial class AyaDbContextModel
    {
        private AyaDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("e6139e18-f8fa-4728-baab-530086c9e98b"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var fileEntity = FileEntityEntityType.Create(this);
            var eventEntity = EventEntityEntityType.Create(this);
            var migrationEntity = MigrationEntityEntityType.Create(this);

            FileEntityEntityType.CreateAnnotations(fileEntity);
            EventEntityEntityType.CreateAnnotations(eventEntity);
            MigrationEntityEntityType.CreateAnnotations(migrationEntity);

            AddAnnotation("ProductVersion", "10.0.1");
        }
    }
}
